= Movies Example Application

How to use Quarkus and Neo4j OGM together. Neo4j OGM enables convenient integration and object-graph mapping (OGM) in your Quarkus application.

The example project is described in detail on the https://neo4j.com/developer/example-project/[Neo4j Developer Site]

The project uses Java 11 and Quarkus 2.12.2.

== The Stack

These are the components of our Web Application:

* Application Type:         Quarkus
* Persistence Access:       Quarkus-Neo4j-OGM
* Database:                 Neo4j-Server 4.x
* Frontend:                 jquery, bootstrap, http://d3js.org/[d3.js]

Provision a database quickly with https://sandbox.neo4j.com/?usecase=movies[Neo4j Sandbox] or https://neo4j.com/cloud/aura/[Neo4j Aura].


== Building &amp; Running

The project is built via Maven:

----
mvn package
----

Additionally, you can execute the integration test, which fires up a local Neo4j instance via Testcontainers:

----
mvn test-compile failsafe:integration-test failsafe:verify
----

You run the Quarkus application via executable JAR:

----
java -jar target/quarkus-app/quarkus-run.jar
----

Then, the application is available under http://localhost:8080/

Alternatively, you can use Quarkus' development mode:

----
mvn quarkus:dev
----

This enables you to edit the Java code while the application keeps running.


=== Running Neo4j Database Locally

Per default, the example runs with a generally-available database under https://demo.neo4jlabs.com:7473

You can also run a local Neo4j database with the example project as Docker container. For this, execute the `./run-graph-db.sh` script, and change the Quarkus application properties (`src/main/resources/application.properties`) as follows:

----
quarkus.neo4j.uri=bolt://localhost:7687
quarkus.neo4j.authentication.username=neo4j
quarkus.neo4j.authentication.password=test
----

If you want to run your Neo4j database in a different way, you can also execute the `:guide movies` in your database console, and execute the long Cypher statement to fill your database with the movie data from the second slide of that guide.


== Understanding the Examples

Once the application is running, you can examine the UI under http://localhost:8080

The different scenarios of finding movies with certain queries and advanced example can be found under the "`Scenarios`" dropdown.

In order to comprehend how the queries are executed, you can follow the code in the link:src/main/java/com/neo4j/examples/movies/quarkus/movies/MovieResource.java[MovieResource], link:src/main/java/com/neo4j/examples/movies/quarkus/search/SearchResource.java[SearchResource], link:src/main/java/com/neo4j/examples/movies/quarkus/persons/ActorsResource.java[ActorsResource], and link:src/main/java/com/neo4j/examples/movies/quarkus/graph/GraphResource.java[GraphResource] classes.

All JAX-RS resource classes access application-scoped beans, such as link:src/main/java/com/neo4j/examples/movies/quarkus/search/Searches.java[Searches], which access the Neo4j database via OGM `Session`.
The OGM session is created via `SessionFactory` which can be injected in the classes since we're using the `org.neo4j:neo4j-ogm-quarkus` dependency in our project:

[source,java]
----
@ApplicationScoped
public class Searches {

    @Inject
    SessionFactory sessionFactory;

    public List<Movie> searchMoviesByTitle(String title) {
        Session session = sessionFactory.openSession();
        Iterable<Movie> iterable = session.query(Movie.class, "MATCH (movie:Movie) WHERE movie.title CONTAINS $title RETURN movie", Map.of("title", title));

        // [...]
    }
}
----
